### ISSUE TITLE
Availability of cell painting results for JUMP-MOA in cellpainting-gallery?

### ISSUE THREAD

**Issue by sooheon** [jump-cellpainting/JUMP-MOA#11]
Thank you for this resource. Are the cellpainting images for this compound set available within the cellpainting gallery? I see other publications with much larger datasets, but I wonder if the MOA set is a subset of any of them, or collected as part of larger initiatives. Thank you.

**Comment by bethac07** [comment]
Hi,

The majority of `cpg0001` was treated with this compound plate; you can check [this table](https://github.com/carpenter-singh-lab/2022_Cimini_NatureProtocols/blob/main/JUMPExperimentMasterTable.csv) to see the exact batches and plate barcodes (for any sets using JUMP-MOA you will see `JUMP-MOA` in the `Treatments` column). Hope that helps!
